name: Digital Ocean

on:
  push:
    branches:
      - features/membership

env:
  REGISTRY: "registry.digitalocean.com/private-registry"
  IMAGE_NAME: "backend-go"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create Docker config file
        run: echo "${{ secrets.DOCKER_CONFIG }}" | base64 --decode > $HOME/.docker/config.json
   
      - name: Build container image
        run: docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
   
      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-$(uname -s)-$(uname -m).tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin
          
      - name: Deploy to DigitalOcean Droplet
        run: |
          doctl auth init --context github-actions --access-token "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
          doctl compute droplet create droplet-name --image $REGISTRY/$IMAGE_NAME:${{ github.sha }} --size droplet-size --region droplet-region --ssh-keys droplet-ssh-key --wait
